spring:
    jpa:
        generate-ddl: true
        database: h2
        show-sql: true
        hibernate:
            ddl-auto: create

    datasource:
        name: accounts
        url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS accounts
        data: classpath:/sql/data.sql
    h2:
        console:
            enabled: true
            path: /console
    application:
        name: accounts
server:
    port: 8082
management:
    endpoints:
        web:
            exposure:
                include: '*'