spring:
    jpa:
        generate-ddl: true
        database: h2
        show-sql: true
        hibernate:
            ddl-auto: create

    datasource:
        name: clients
        url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS clients
        data: classpath:/sql/data.sql
    h2:
        console:
            enabled: true
            path: /clients-console
    application:
        name: clients
server:
    port: 8083
management:
    endpoints:
        web:
            exposure:
                include: '*'